apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: cragr-cragr-poi-map-app-dev
  annotations:
    argocd/app-name: cragr-cragr-poi-map-app-dev
    backstage.io/kubernetes-id: cragr-cragr-poi-map-app-dev
    backstage.io/kubernetes-namespace: cragr
    backstage.io/kubernetes-label-selector: 'app.kubernetes.io/instance=cragr-cragr-poi-map-app-dev'
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: Summit23Janus2/cragr-frontend
    janus-idp.io/tekton-enabled: 'true'
  tags:
    - typescript
    - angular
    - workshop
  links:
    - url: https://console-openshift-console.apps.summit23blues.6mbu.p1.openshiftapps.com/dev-pipelines/ns/cragr/
      title: Pipelines
      icon: web
    - url: https://console-openshift-console.apps.summit23blues.6mbu.p1.openshiftapps.com/k8s/ns/cragr/deployments/cragr-poi-map-app
      title: Deployment
      icon: web
    - url: https://devspaces.apps.summit23blues.6mbu.p1.openshiftapps.com/#https://github.com/Summit23Janus2/cragr-frontend?che-editor=che-incubator/che-code/latest&devfilePath=.devfile-vscode.yaml
      title: OpenShift Dev Spaces (VS Code)
      icon: web
    - url: http://cragr-poi-map-app-cragr.apps.summit23blues.6mbu.p1.openshiftapps.com
      title: Map
      icon: web
spec:
  type: service
  lifecycle: production
  owner: "cragr"
  system: workshop-system-cragr
  consumesApis:
    - gateway-api-cragr
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: workshop-system-cragr
  tags:
    - backstage
    - janus-idp
    - openshift
    - workshop
    - rh-summit
spec:
  owner: "cragr"
